// <auto-generated />
using System;
using FeedbackClientes.RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedbackClientes.RazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230905023634_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("FeedbackClientes.RazorPages.Models.FeedbackModel", b =>
                {
                    b.Property<int?>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Avaliação")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentário")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFeedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdFeedback");

                    b.ToTable("Feeedbacks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
